language: ruby
rvm:
- 2.2
- 2.1
- 1.9.3
sudo: required
services:
- docker
script:
- >
  wget -O- bit.ly/ansibletest | env
  DOCKER_IMAGES="ubuntu:14.04 ubuntu:16.04 debian:stretch"
  ANSIBLE_VERSIONS="1.4.4 1.6.1 1.9.2 2.0.0.2 2.1.0.0"
  sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
